version: "3"

services:
  app:
    container_name: app-container
    restart: always
    ports:
      - published: ${REACT_APP_PORT}
        target: ${REACT_APP_PORT}
      - published: ${DB_STUDIO_PORT}
        target: ${DB_STUDIO_PORT}
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
